PetsZone/PetsZone/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import login_page,register_page,guest_register_view
from .views import home_page, about_page, contact_page
from django.contrib.auth.views import LogoutView
from addresses.views import checkout_address_create_view,checkout_address_reuse_view
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page,name='home'),
    path('about/', about_page,name='about'),
    path('contact/', contact_page,name='contact'),
    path('login/', login_page,name='login'),
    path('checkout/address/create/', checkout_address_create_view, name='checkout_address_create'),
    path('checkout/address/reuse/', checkout_address_reuse_view, name='checkout_address_reuse'),
    path('register/guest/', guest_register_view, name='guest_register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', register_page,name='register'),
    path('cart/', include("carts.urls", namespace="cart")),
   # path('bootstrap/', TemplateView.as_view(template_name="bootstrap/example.html")),
    path('product1/', include("product1.urls", namespace="product1")),
    path('search/', include("search.urls", namespace="search"))

]


if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
  

PetsZone/carts/urls.py
from django.urls import path


from .views import cart_home,cart_update,checkout_home,checkout_done_view
app_name = 'carts'
urlpatterns = [
   
    path('', cart_home, name="home"),
   path('checkout/', checkout_home, name="checkout"),
   path('checkout/success/', checkout_done_view, name="success"),
    path('update/', cart_update, name="update"),
   
]  

PetsZone/product1/urls.py
from django.urls import path


from .views import productlistview,productdetailslugview
app_name = 'product1'
urlpatterns = [
   
    path('', productlistview.as_view(), name="list"),
   
    path('<slug:slug>/', productdetailslugview.as_view(), name="detail"),
   
]  

PetsZone/templates/base.html
{% load static %}

<!DOCTYPE html>
    <html lang="en">
    <head>
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>base templete</title>
    {% include 'base/css.html' %}
    </head>
    <body>
      {% include 'base/navbar.html' with brand_name="PetsZone" %}
       
      <div class="container">
      {% block content %} {% endblock %}  
     </div>

     {% include 'base/js.html' %}

    </body>
  </html>

PetsZone/templates/home_page.html
{% load static %}
    <title>home templete</title>
{% block content %}
 <div class='text-center'>
          
      </div>
    
        <div class='row'>
          <div class='col'>
              
              {% include 'homepage.html' %}
              <p>{{ content }}</p>
          </div>
        </div>
        {% if request.user.is_authenticated %}
        <div class='row'>
          <div class='col'>
          <h1>Premium</h1>
          {{ premium_content }}
          </div>
        </div>
        {% endif %}
    
{% endblock %}

PetsZone/templates/homepage.html
{% load static %}
{% url 'home' as home_url %}
{% url 'contact' as contact_url %}
{% url 'login' as login_url %}
{% url 'product1:list' as product1_list_url %}
{% url 'register' as register_url %}
{% url 'cart:home' as cart_url %}
{% url 'logout' as logout_url %}
<!DOCTYPE html>
<html>
<title>Petz Zone</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
.w3-sidebar a {font-family: "Roboto", sans-serif}
body,h1,h2,h3,h4,h5,h6,.w3-wide {font-family: "Montserrat", sans-serif;}
</style>
<body class="w3-content" style="max-width:1200px">

<!-- Sidebar/menu -->
<nav class="w3-sidebar w3-bar-block w3-white w3-collapse w3-top" style="z-index:3;width:250px" id="mySidebar">
  <div class="w3-container w3-display-container w3-padding-16">
    <i onclick="w3_close()" class="fa fa-remove w3-hide-large w3-button w3-display-topright"></i>
    <h3 class="w3-wide"><b><a href="{{ home_url }}">PetsZone</a></b></h3>
  </div>
  <div class="w3-padding-64 w3-large w3-text-grey" style="font-weight:bold">
<a href="{{ product1_list_url }}" class="w3-bar-item w3-button">Pets</a>
  <a onclick="myAccFunc()" href="javascript:void(0)" class="w3-button w3-block w3-white w3-left-align" id="myBtn">
      Dogs <i class="fa fa-caret-down"></i>
    </a>
    

    <div id="demoAcc" class="w3-bar-block w3-hide w3-padding-large w3-medium">
           <a href="{{ product1_list_url }}" class="w3-bar-item w3-button">pitbull</a>
      <a href="{{ product1_list_url }}" class="w3-bar-item w3-button">German shepherd</a>
      <a href="{{ product1_list_url }}" class="w3-bar-item w3-button">Doberman</a>
    </div>


    
     <a href="{{ product1_list_url }}" class="w3-bar-item w3-button">Puppies</a>
    <a href="{{ product1_list_url }}" class="w3-bar-item w3-button">Cats</a>
    
    <a href="{{ product1_list_url }}" class="w3-bar-item w3-button">Birds</a>
   
  </div>
  {% if request.user.is_authenticated %}
       <li class="nav-item {% if request.path == logout_url %}active{% endif %}">
        <a class="nav-link" href="{{ logout_url }}">logout</a>
        {% else %}</li>
               <li class="nav-item {% if request.path == register_url %}active{% endif %}">
        <a class="nav-link" href="{{ register_url }}">Signup</a></li>
               <li class="nav-item {% if request.path == login_url %}active{% endif %}">
        <a class="nav-link" href="{{ login_url }}">login</a>
         </li>
        {% endif %}
 
  <a href="#footer" class="w3-bar-item w3-button w3-padding">Contact</a> 
  <a href="javascript:void(0)" class="w3-bar-item w3-button w3-padding" onclick="document.getElementById('newsletter').style.display='block'">Newsletter</a> 
  <a href="#footer"  class="w3-bar-item w3-button w3-padding">Subscribe</a>
</nav>

<!-- Top menu on small screens -->
<header class="w3-bar w3-top w3-hide-large w3-black w3-xlarge">
  <div class="w3-bar-item w3-padding-24 w3-wide">LOGO</div>
  <a href="javascript:void(0)" class="w3-bar-item w3-button w3-padding-24 w3-right" onclick="w3_open()"><i class="fa fa-bars"></i></a>
</header>

<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:250px">

  <!-- Push down content on small screens -->
  <div class="w3-hide-large" style="margin-top:83px"></div>
  
  <!-- Top header -->
  <header class="w3-container w3-xlarge">
    <p class="w3-left">Pets</p>
    <p class="w3-right">
       <li class="nav-item {% if request.path == cart_url %}active{% endif %}">
        <a class="fa fa-shopping-cart w3-margin-right" href="{{ cart_url }}"> {{ request.session.cart_items }}</a>
     {% include 'search/snippets/search-form.html' %}
    
    </p>
  </header>

  <!-- Image header -->
  <div class="w3-display-container w3-container">
    {% include 'slideshow.html' %}
    <div class="w3-display-topleft w3-text-white" style="padding:24px 48px">
      <h1 class="w3-jumbo w3-hide-small"></h1>
      <h1 class="w3-hide-large w3-hide-medium"></h1>
      <h1 class="w3-hide-small"></h1>
      <p><a href="{{ product1_list_url }}" class="w3-button w3-black w3-padding-large w3-large">SHOP NOW</a></p>
    </div>
  </div>

  <div class="w3-container w3-text-grey" id="jeans">
    <p>8 items</p>
  </div>

  <!-- Product grid -->
  <div class="w3-row w3-grayscale">
    <div class="w3-col l3 s6">
      <div class="w3-container">
        <img src="{% static 'img/Dogs/shepherd1.jpg' %}" style="width:100%">
        <p><a href="{{ product1_list_url }}">German Shepherd Dog<br><b>Rs.5000</b></p>
      </div>
      <div class="w3-container">
        <img src="{% static 'img/Dogs/bull.jpg' %}" style="width:100%">
        <p>Bull dog<br><b>Rs.5050</b></p>
      </div>
    </div>

    <div class="w3-col l3 s6">
      <div class="w3-container">
        <div class="w3-display-container">
          <img src="{% static 'img/Dogs/BostonTerrier.jpg' %}" style="width:100%">
          <span class="w3-tag w3-display-topleft">New</span>
          <div class="w3-display-middle w3-display-hover">
            <button class="w3-button w3-black">Buy now <i class="fa fa-shopping-cart"></i></button>
          </div>
        </div>
        <p>BostonTerrier Dog<br><b>Rs.2000</b></p>
      </div>
      <div class="w3-container">
        <img src="{% static 'img/Dogs/pitbull.jpg' %}" style="width:100%">
        <p>pitbull<br><b>Rs.4000</b></p>
      </div>
    </div>

    <div class="w3-col l3 s6">
      <div class="w3-container">
        <img src="{% static 'img/Cat/PersianCat.jpg' %}" style="width:100%">
        <p>Persian Cat<br><b>Rs.1000</b></p>
      </div>
      <div class="w3-container">
        <div class="w3-display-container">
          <img src="{% static 'img/Cat/MaineCoon.jpg' %}" style="width:100%">
         
          <div class="w3-display-middle w3-display-hover">
            <button class="w3-button w3-black">Buy now <i class="fa fa-shopping-cart"></i></button>
          </div>
        </div>
        <p>MaineCoon<br><b class="w3-text-red">Rs.500</b></p>
      </div>
    </div>

    <div class="w3-col l3 s6">
      <div class="w3-container">
        <img src="{% static 'img/Bird/Perrot.jpg' %}" style="width:100%">
        <p>Parrot Bird<br><b>Rs.650</b></p>
      </div>
      <div class="w3-container">
        <img src="{% static 'img/Bird/pigeon.jpg' %}" style="width:100% ">
        <p>Pigeon Bird<br><b>Rs.300</b></p>
      </div>
    </div>
  </div>

  <!-- Subscribe section -->
  <div class="w3-container w3-black w3-padding-32">
    <h1>Subscribe</h1>
    <p>To get special offers and VIP treatment:</p>
    <p><input class="w3-input w3-border" type="text" placeholder="Enter e-mail" style="width:100%"></p>
    <button type="button" class="w3-button w3-red w3-margin-bottom">Subscribe</button>
  </div>
  
  <!-- Footer -->
  <footer class="w3-padding-64 w3-light-grey w3-small w3-center" id="footer">
    <div class="w3-row-padding">
      <div class="w3-col s4">
        <h4>Contact</h4>
        <p>Questions? Go ahead.</p>
        <form action="/action_page.php" target="_blank">
          <p><input class="w3-input w3-border" type="text" placeholder="Name" name="Name" required></p>
          <p><input class="w3-input w3-border" type="text" placeholder="Email" name="Email" required></p>
          <p><input class="w3-input w3-border" type="text" placeholder="Subject" name="Subject" required></p>
          <p><input class="w3-input w3-border" type="text" placeholder="Message" name="Message" required></p>
          <button type="submit" class="w3-button w3-block w3-black">Send</button>
        </form>
      </div>

      <div class="w3-col s4">
        <h4>About</h4>
        <p><a href="#">About us</a></p>
        <p><a href="#">We're hiring</a></p>
        <p><a href="#">Support</a></p>
        <p><a href="#">Find store</a></p>
        <p><a href="#">Shipment</a></p>
        <p><a href="#">Payment</a></p>
        <p><a href="#">Gift card</a></p>
        <p><a href="#">Return</a></p>
        <p><a href="#">Help</a></p>
      </div>

      <div class="w3-col s4 w3-justify">
        <h4>Store</h4>
        <p><i class="fa fa-fw fa-map-marker"></i> Company Name</p>
        <p><i class="fa fa-fw fa-phone"></i> 0044123123</p>
        <p><i class="fa fa-fw fa-envelope"></i> ex@mail.com</p>
        <h4>We accept</h4>
        <p><i class="fa fa-fw fa-cc-amex"></i> Amex</p>
        <p><i class="fa fa-fw fa-credit-card"></i> Credit Card</p>
        <br>
        <i class="fa fa-facebook-official w3-hover-opacity w3-large"></i>
        <i class="fa fa-instagram w3-hover-opacity w3-large"></i>
        <i class="fa fa-snapchat w3-hover-opacity w3-large"></i>
        <i class="fa fa-pinterest-p w3-hover-opacity w3-large"></i>
        <i class="fa fa-twitter w3-hover-opacity w3-large"></i>
        <i class="fa fa-linkedin w3-hover-opacity w3-large"></i>
      </div>
    </div>
  </footer>

  <div class="w3-black w3-center w3-padding-24">Powered by <a href="https://www.w3schools.com/w3css/default.asp" title="W3.CSS" target="_blank" class="w3-hover-opacity">PetsZone.com</a></div>

  <!-- End page content -->
</div>

<!-- Newsletter Modal -->
<div id="newsletter" class="w3-modal">
  <div class="w3-modal-content w3-animate-zoom" style="padding:32px">
    <div class="w3-container w3-white w3-center">
      <i onclick="document.getElementById('newsletter').style.display='none'" class="fa fa-remove w3-right w3-button w3-transparent w3-xxlarge"></i>
      <h2 class="w3-wide">NEWSLETTER</h2>
      <p>Join our mailing list to receive updates on new arrivals and special offers.</p>
      <p><input class="w3-input w3-border" type="text" placeholder="Enter e-mail"></p>
      <button type="button" class="w3-button w3-padding-large w3-red w3-margin-bottom" onclick="document.getElementById('newsletter').style.display='none'">Subscribe</button>
    </div>
  </div>
</div>

<script>
// Accordion 
function myAccFunc() {
    var x = document.getElementById("demoAcc");
    if (x.className.indexOf("w3-show") == -1) {
        x.className += " w3-show";
    } else {
        x.className = x.className.replace(" w3-show", "");
    }
}

// Click on the "Jeans" link on page load to open the accordion for demo purposes
document.getElementById("myBtn").click();


// Script to open and close sidebar
function w3_open() {
    document.getElementById("mySidebar").style.display = "block";
    document.getElementById("myOverlay").style.display = "block";
}
 
function w3_close() {
    document.getElementById("mySidebar").style.display = "none";
    document.getElementById("myOverlay").style.display = "none";
}
</script>

</body>
</html>

PetsZone/templates/slideshow.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
  
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <div class="item active">
        <img src="{% static 'img/Dogs/pub1.jpg' %}" alt="Dog" style="width:100%;">
      </div>

      <div class="item">
        <img src="{% static 'img/Bird/Perrot.jpg' %}" alt="Chicago" style="width:100%;">
      </div>
    
      <div class="item">
        <img src="{% static 'img/Cat/PersianCat.jpg' %}" alt="New york" style="width:100%;">
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

</body>
</html>